# Generated by Django 2.2.3 on 2019-07-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorites',
            new_name='favourites',
        ),
    ]
