# Generated by Django 2.2.3 on 2019-07-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190718_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favourites',
            new_name='favorite',
        ),
    ]
