# Generated by Django 2.2.3 on 2019-07-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190718_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
